### ISSUE TITLE
New alpha release broke

### ISSUE THREAD

**Issue by perrin4869** [istanbuljs/istanbul-api#4]
My module stopped producing coverage reports with the new `v1.1.0-alpha.1` version with the following error:

```
TypeError: libReport.createReportSource is not a function
    at Object.Reporter.write (/home/perrin4869/projects/nodejs/gulp-i18next-conv/node_modules/istanbul-api/lib/reporter.js:80:34)
    at exitFn (/home/perrin4869/projects/nodejs/gulp-i18next-conv/node_modules/istanbul-api/lib/run-cover.js:127:18)
    at process.g (events.js:286:16)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:79:15)
    at done (/home/perrin4869/projects/nodejs/gulp-i18next-conv/node_modules/mocha/bin/_mocha:417:32)
    at afterWrite (_stream_writable.js:360:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Source is here: https://github.com/perrin4869/gulp-i18next-conv

Run `npm run cover` to run coverage.

**Comment by gotwarlost** [comment]
Could you please delete your `node_modules` folder and re-install everything? See also https://github.com/gotwarlost/istanbul/issues/655

**Comment by perrin4869** [comment]
Still failing :/

**Comment by gotwarlost** [comment]
Could you actually change the istanbul dependency to `^1.1.0-alpha` (up minor version). This problem is actually with the old version of istanbul which for some reason has started to appear after publishing `1.1.x` (see the other thread for more info). I can only look at this ~30 hours from now.

**Comment by perrin4869** [comment]
Yup, that fixed it, thanks!
